#!/bin/bash

ISCSIADM=/sbin/iscsiadm
SESSION_FILE=/run/initramfs/iscsi.sessions

if [ ! -f $SESSION_FILE ] ; then
  exit 0
fi

while read t num i target; do
  ip=${i%:*}
  $ISCSIADM -m node -p $ip -T $target -o update -n node.startup -v onboot
done < $SESSION_FILE

